### ISSUE TITLE
[feat] 메인과 핫페이지에 데이터를 받아와 출력

### ISSUE THREAD

**Issue by gd06070** [prgrms-fe-devcourse/NFE1_2_Youngstar#29]
## 💡 Feature Issue
> 메인 페이지, 핫 페이지 데이터 출력 작업

## 🌿  To-do
> 해야 할 일들을 적어주세요
- [x] 메인페이지에 포스트 한 데이터 가져오기
- [x] 메인페이지에 데이터 출력
- [x] 핫페이지에 포스트 한 데이터 가져오기
- [x] 핫페이지에 데이터 출력

## 📚Reference
> 참고할 자료가 있다면 적어주세요
