### ISSUE TITLE
[feat] 메인 페이지

### ISSUE THREAD

**Issue by shwnsl** [prgrms-fe-devcourse/NFE1_2_Youngstar#3]
## 💡 Feature Issue
> 메인 페이지 마크업

## 🌿  To-do
- [x] Header 컴포넌트 추가
- [x] Navbar 컴포넌트 추가
- [x] Follower 컴포넌트 추가
- [x] Post 컴포넌트 추가
- [x] 각 컴포넌트 별 반응형 추가

## 📚Reference
> <img src='https://github.com/user-attachments/assets/52e20270-8355-4780-b96c-4e5ac7db6e09'>
