### ISSUE TITLE
[feat] 알림페이지에 데이터를 받아와 출력

### ISSUE THREAD

**Issue by snsdl0905** [prgrms-fe-devcourse/NFE1_2_Youngstar#39]
## 💡 Feature Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요

알림페이지에 데이터를 받아와서 출력합니다.

## 🌿  To-do
> 해야 할 일들을 적어주세요
- [ ] 사용자에게 온 알림을 출력힌다.
- [ ] 읽은 알림과, 읽지 않은 알림을 색으로 구분한다.
- [ ] 읽지 않은 알림을 누르면 읽은 것으로 처리한다.

## 📚Reference
> 참고할 자료가 있다면 적어주세요
