### ISSUE TITLE
[feat] 마이페이지에 사용자 정보 및 작성한 글 데이터를 받아와 출력

### ISSUE THREAD

**Issue by snsdl0905** [prgrms-fe-devcourse/NFE1_2_Youngstar#40]
## 💡 Feature Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요
마이페이지에 데이터를 출력합니다.

## 🌿  To-do
> 해야 할 일들을 적어주세요
- [ ] 사용자의 이름이 출력됩니다.
- [ ] 사용자가 작성한 포스트들이 보입니다.
- [ ] 사용자의 팔로워와 팔로잉 목록이 보입니다.

## 📚Reference
> 참고할 자료가 있다면 적어주세요
