### ISSUE TITLE
[fix] 데이터 요청 링크 수정 및 페이지 연결

### ISSUE THREAD

**Issue by snsdl0905** [prgrms-fe-devcourse/NFE1_2_Youngstar#46]
## 💡 Feature Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요

현재는 한 데이터를 골라서 출력하는 식으로 구현되어있습니다.

## 🌿  To-do
> 해야 할 일들을 적어주세요
- [ ] 토큰을 사용하여 마이페이지의 정보를 불러온다.
- [ ] 마이페이지의 게시글을 누르면 해당 포스트로 이동한다.
- [ ] 알림페이지의 알림을 누르면 읽음 처리한다.
- [ ] 알림페이지의 알림을 누르면 알림과 관련된 페이지로 이동한다.
- [ ] 토큰이 없는 상태로 마이페이지를 클릭하면 로그인 페이지로 연결한다.

## 📚Reference
> 참고할 자료가 있다면 적어주세요
