### ISSUE TITLE
[feat] 검색 기능 수정

### ISSUE THREAD

**Issue by snsdl0905** [prgrms-fe-devcourse/NFE1_2_Youngstar#59]
## 💡 Feature Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요

검색 기능 구현 및 글 수정, 삭제와 같은 자잘한 기능들을 구현, 수정 할 예정입니다

## 🌿  To-do
> 해야 할 일들을 적어주세요
- [ ] 검색 기능 구현
- [ ] 글 수정 기능 구현
- [ ] 글 삭제 기능 구현
- [ ] 팔로우 및 팔로잉 기능 구현
- [ ] 실시간 또는 모든 사용자 목록 출력

## 📚Reference
> 참고할 자료가 있다면 적어주세요
