### ISSUE TITLE
[feat] 글 상세 모달창 구현

### ISSUE THREAD

**Issue by snsdl0905** [prgrms-fe-devcourse/NFE1_2_Youngstar#8]
## 💡 Feature Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요

포스트를 눌렀을 때 포스트에 대한 상세페이지를 디자인대로 구현합니다.

## 🌿  To-do
> 해야 할 일들을 적어주세요
- [ ] 포스트의 사진이 보인다.
- [ ] 포스트의 본문 내용이 보인다.
- [ ] 포스트 댓글 목록과 댓글이 보인다.
- [ ] 댓글 입력창이 존재한다.

## 📚Reference
> 참고할 자료가 있다면 적어주세요
![image](https://github.com/user-attachments/assets/e9b5a7e9-df49-4db0-9e4d-fd3392b62754)

홈 화면의 포스트 컴포넌트에 본문과 댓글, 입력창이 추가된 형태로 구현 될 예정입니다.
